#ice-substrate artifact deployment on dev environments
name: ice-substrate artifact deployment on dev environments

on:
  push:
    branches: [ main ]

jobs:
       
  copy-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create downloads dir
        run: 
          mkdir downloads
      - name: change directory
        run:  
          cd downloads
      - name: copy artifact
        run:      
          wget https://github.com/web3labs/ice-substrate/releases/download/v0.2.0/ice-node-.zip
      - name: unzip artifact
        run:
          unzip ice-*.zip
      - name: remove zip
        run:
          rm -rvf ice-*.zip        
          
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: ice-node
          path: .
       
  deploy-rpc:
    needs: copy-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_RPC }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_RPC }} >> ~/.ssh/known_hosts

      - uses: actions/download-artifact@v2
        with:
          name: ice-node
          path: .
      
      - name: deploy with rsync
        run: rsync -avz ice* ${{ secrets.SSH_USER_RPC }}@${{ secrets.SSH_HOST_RPC }}:/root/ice-node/
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_RPC }}
          username: ${{ secrets.SSH_USER_RPC }}
          key: ${{ secrets.SSH_PRIVATE_KEY_RPC }}
          port: ${{ secrets.SSH_PORT }}
          script: sh /root/ice-node/rpcrestart.sh
        
  deploy-validator:
    needs: deploy-rpc
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_VALID }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_VALID }} >> ~/.ssh/known_hosts

      - uses: actions/download-artifact@v2
        with:
          name: ice-node
          path: .
      
      - name: deploy with rsync
        run: rsync -avz ice* ${{ secrets.SSH_USER_VALID }}@${{ secrets.SSH_HOST_VALID }}:/root/ice-node/
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_VALID }}
          username: ${{ secrets.SSH_USER_VALID }}
          key: ${{ secrets.SSH_PRIVATE_KEY_VALID }}
          port: ${{ secrets.SSH_PORT }}
          script: sh /root/ice-node/validrestart.sh
  
