#Scaleway auto-SSH key update workflow
name: Scaleway auto-SSH key update workflow

on: 
  workflow_dispatch:
    inputs:
      sshkey:
        description: 'Your Public Key'
        required: true
      hostip:
        description: 'Host IP'
        required: true
              
jobs:
       
  deploy-sshkey:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_RPC }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_RPC }} >> ~/.ssh/known_hosts

      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_RPC }}
          username: ${{ secrets.SSH_USER_RPC }}
          key: ${{ secrets.SSH_PRIVATE_KEY_RPC }}
          port: ${{ secrets.SSH_PORT }}
          script: sh /scripts/test.sh ${{ github.event.inputs.hostip }} ${{ github.event.inputs.sshkey }}
